name: Kwiki-AdSense
version: 0.11
abstract: Google AdSense Plugin For Kwiki
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
